spring:
  application:
    name: 9oormthonUniv-2025-seasonthon-team-54-be

  profiles:
    # 실행 시 활성화할 프로파일은 외부에서 지정 (--spring.profiles.active=local 등)
    active: local

# Swagger(OpenAPI) 공통 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# 기본 로깅 레벨
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
