spring:
  application:
    name: ssg-tab

  profiles:
    # 실행 시 활성화할 프로파일은 외부에서 지정 (--spring.profiles.active=local 등)
    active: local
  jpa:
    hibernate:
      ddl-auto: update  # 선택: create, update, validate 등
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6380
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  # Azure Blob Storage
  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
          account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
          endpoint: ${AZURE_STORAGE_ENDPOINT}


# Swagger(OpenAPI) 공통 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jwt:
  issuer: ssg-tab
  secret: ${JWT_SECRET_KEY}
  access-token-exp-min: 60  # 60분
  refresh-token-exp-days: 14    # 14일

# 기본 로깅 레벨
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace


