name: CI (Build and Test)

# main 브랜치로 향하는 Pull Request가 생성/업데이트될 때 실행
on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # 테스트용 DB 컨테이너 설정
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ssg
          MYSQL_DATABASE: ssg
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test with Gradle
        # CI 단계에서는 테스트를 포함하여 빌드를 실행
        run: ./gradlew build
        env:
          DB_HOST: 127.0.0.1:3306
          DB_NAME: ssg
          DB_USER: root
          DB_PASSWORD: ssg